### ISSUE TITLE
Dopuniti SRS dokument UML dijagramima

### ISSUE THREAD

**Issue by BakirK** [RPR-2019/nrs_projekat_tim3#7]
Potrebno je dopuniti SRS dokument svim bitnim UML dijagramima a posebno dijagramima slučajeva upotrebe i dijagramima aktivnosti.

**Comment by Kerim246** [comment]
![dijagramRadnik](https://user-images.githubusercontent.com/48659111/79688080-0ae31100-824c-11ea-9250-cb52746c8add.png)

![dijagramMenadzer](https://user-images.githubusercontent.com/48659111/79688081-0c143e00-824c-11ea-9bad-fde5231be5f9.png)

![dijagramKorisnik](https://user-images.githubusercontent.com/48659111/79688076-061e5d00-824c-11ea-81fb-890e5d2f05e4.png)
