### ISSUE TITLE
Kreirati dokument dizajn sistema

### ISSUE THREAD

**Issue by BakirK** [RPR-2019/nrs_projekat_tim3#8]
Kreirati dokument "Dizajn sistema" koji će predstavljati detaljan opis dizajna buduće aplikacije. Dokument obavezno mora sadržavati minimalno:
* dijagram entitet-veza
* dijagram klasa
* dijagram raspoređivanja
* dijagram komponenti
Pored toga, dopunite dokument i drugim dijagramima za koje smatrate da su bitne.

**Comment by DalilaHerh** [comment]
![erd](https://user-images.githubusercontent.com/48456922/79689592-23f0bf80-8256-11ea-868d-b817e7ddc7bb.PNG)

**Comment by DalilaHerh** [comment]
![Dijagram klasa](https://user-images.githubusercontent.com/48456922/79694689-3aa50f80-8272-11ea-89d1-b329c7b88f05.png)

**Comment by BakirK** [comment]
![image](https://user-images.githubusercontent.com/16404799/79695649-53b0bf00-8278-11ea-8cce-e5f270025018.png)
Deployment diagram

**Comment by BakirK** [comment]
![image](https://user-images.githubusercontent.com/16404799/79698923-7056f200-828c-11ea-932f-842aefeeabb6.png)
Component diagram (black box)

**Comment by TajmaMahmutovicETF** [comment]
Zasto vam je dizajn on hold?

**Comment by TajmaMahmutovicETF** [comment]
Ok su vam dijagram komponenti i deployment dijagram, ali pojednostavite malo ERD, izvršite reviziju.

**Comment by BakirK** [comment]
Dodan novi ERD da ne bi doslo do zabune
![ERD](https://user-images.githubusercontent.com/16404799/83355727-9ed2ed00-a361-11ea-8265-c0c65f8920f3.png)
