### ISSUE TITLE
Dizajn korisničkog interfejsa

### ISSUE THREAD

**Issue by BakirK** [RPR-2019/nrs_projekat_tim3#9]
U dokument dizajn sistema dodati dizajn korisni;kog interfejsa u kojem treba specificirati korsinički interfejs prema pravilima naučenim na predmetu "Interakcija čovjek-računar".

**Comment by Harun292** [comment]
![add_edit_product_layout](https://user-images.githubusercontent.com/48387572/79687177-b046b680-8245-11ea-9cc8-2f107d8a51ff.PNG)
![add_edit_employee_layout](https://user-images.githubusercontent.com/48387572/79687188-b9d01e80-8245-11ea-8c81-355c9cecd32d.PNG)
![edit_warehouse_layout](https://user-images.githubusercontent.com/48387572/79687191-bf2d6900-8245-11ea-8b50-07713c137bb4.PNG)
![warehouses_layout](https://user-images.githubusercontent.com/48387572/79687197-c3f21d00-8245-11ea-9328-d1dbfc7a2fd3.PNG)
![add_warehouse_layout](https://user-images.githubusercontent.com/48387572/79687199-c8b6d100-8245-11ea-9b8f-cfaba92c1f32.PNG)
![profile_layout](https://user-images.githubusercontent.com/48387572/79687203-cf454880-8245-11ea-876c-2bf8bb151e21.PNG)
![employee_layout](https://user-images.githubusercontent.com/48387572/79687206-d3716600-8245-11ea-9f48-2ea515397ce2.PNG)
![web_shop_layout](https://user-images.githubusercontent.com/48387572/79687312-bb4e1680-8246-11ea-940d-82b2ec5ce34f.PNG)
![login_layout](https://user-images.githubusercontent.com/48387572/79687358-036d3900-8247-11ea-9d48-fe0c799a8726.PNG)
